//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TestSrv.rc
//
#define IDS_NTSERV_INSTALL_FAIL_OPEN_SCM 1
#define IDS_NTSERV_INSTALL_FAIL_LOCK_SCM 2
#define IDS_NTSERV_INSTALL_FAIL_CREATESERVICE 3
#define IDS_NTSERV_INSTALL_FAIL_INSTALL_AS_EVENT_LOG_SOURCE 4
#define IDS_NTSERV_INSTALL_FAIL_CHANGEDESCRIPTION 5
#define IDS_NTSERV_INSTALL_FAIL_CHANGESIDINFO 6
#define IDS_NTSERV_INSTALL_FAIL_CHANGEDELAYAUTOSTART 7
#define IDS_NTSERV_INSTALL_FAIL_CHANGEPRIVILEGES 8
#define IDS_NTSERV_INSTALL_FAIL_CHANGEPRESHUTDOWNTIMEOUT 9
#define IDS_NTSERV_INSTALL_FAIL_CHANGELAUNCHPROTECTED 10
#define IDS_NTSERV_INSTALL_GET_DEPENDENCIES 11
#define IDS_NTSERV_UNINSTALL_FAIL_OPEN_SCM 12
#define IDS_NTSERV_UNINSTALL_FAIL_OPEN_SERVICE 13
#define IDS_NTSERV_UNINSTALL_FAIL_WAIT_FOR_STOP 14
#define IDS_NTSERV_UNINSTALL_FAIL_DELETE_SERVICE 15
#define IDS_NTSERV_UNINSTALL_FAIL_UNINSTALL_EVENTLOG_SOURCE 16
#define IDS_NTSERV_UNINSTALL_FAIL_STOP  17
#define IDS_NTSERV_FAIL_START_SERVICE   18
#define IDS_NTSERV_FAIL_STOP_SERVICE    19
#define IDS_NTSERV_FAIL_CONTINUE_SERVICE 20
#define IDS_NTSERV_FAIL_PAUSE_SERVICE   21
#define IDS_NTSERV_FAIL_START_SERVICE5  22
#define IDS_NTSERV_FAIL_GET_MODULE_FILENAME 23
#define IDS_NTSERV_VERBOSE_ERROR_STRING 24
#define IDS_NTSERV_SETSERVICETOSTATUS_FAIL_OPEN_SCM 25
#define IDS_NTSERV_SETSERVICETOSTATUS_FAIL_OPEN_SERVICE 26
#define IDS_NTSERV_SETSERVICETOSTATUS_FAIL_START 27
#define IDS_NTSERV_SETSERVICETOSTATUS_FAIL_CONTINUE 28
#define IDS_NTSERV_SETSERVICETOSTATUS_FAIL_PAUSE 29
#define IDS_NTSERV_SETSERVICETOSTATUS_FAIL_STOP 30
#define IDS_NTSERV_SETSERVICETOSTATUS_FAIL_WAITFORCHANGE 31
#define IDS_NTSERV_SETSERVICETOSTATUS_FAIL_QUERYSTATUS 32

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
